// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsHEbwB0pcXDR_v4vyWn6HyxPu0z9OSHc',
    appId: '1:508743071029:web:0063b2a9135230808b887c',
    messagingSenderId: '508743071029',
    projectId: 'instagram-94aa2',
    authDomain: 'instagram-94aa2.firebaseapp.com',
    storageBucket: 'instagram-94aa2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmDWfVBDh5MIwi7BwqvrTx9bXWMnXx8U',
    appId: '1:508743071029:android:d218a845417799aa8b887c',
    messagingSenderId: '508743071029',
    projectId: 'instagram-94aa2',
    storageBucket: 'instagram-94aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWON1MqCJMthRNwqkAtSLCAeRBkhxCOA',
    appId: '1:508743071029:ios:6a4a2b0321fe5cd48b887c',
    messagingSenderId: '508743071029',
    projectId: 'instagram-94aa2',
    storageBucket: 'instagram-94aa2.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWON1MqCJMthRNwqkAtSLCAeRBkhxCOA',
    appId: '1:508743071029:ios:9fc107c7d98044dc8b887c',
    messagingSenderId: '508743071029',
    projectId: 'instagram-94aa2',
    storageBucket: 'instagram-94aa2.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
